import type { Condition, JsonMap, JsonValue, PolicyContext, ReviewPolicy } from './types.js';
export declare function policy<TPayload extends JsonMap = JsonMap, TMeta extends JsonMap = JsonMap>(input: ReviewPolicy<TPayload, TMeta>): ReviewPolicy<TPayload, TMeta>;
export declare function all<TPayload extends JsonMap = JsonMap, TMeta extends JsonMap = JsonMap>(...conditions: Condition<TPayload, TMeta>[]): Condition<TPayload, TMeta>;
export declare function any<TPayload extends JsonMap = JsonMap, TMeta extends JsonMap = JsonMap>(...conditions: Condition<TPayload, TMeta>[]): Condition<TPayload, TMeta>;
export declare function not<TPayload extends JsonMap = JsonMap, TMeta extends JsonMap = JsonMap>(condition: Condition<TPayload, TMeta>): Condition<TPayload, TMeta>;
export declare function eq<TPayload extends JsonMap = JsonMap, TMeta extends JsonMap = JsonMap>(path: string, expected: JsonValue): Condition<TPayload, TMeta>;
export declare function includes<TPayload extends JsonMap = JsonMap, TMeta extends JsonMap = JsonMap>(path: string, expected: JsonValue): Condition<TPayload, TMeta>;
export declare function numberAbove<TPayload extends JsonMap = JsonMap, TMeta extends JsonMap = JsonMap>(path: string, minimumExclusive: number): Condition<TPayload, TMeta>;
export declare function numberBelow<TPayload extends JsonMap = JsonMap, TMeta extends JsonMap = JsonMap>(path: string, maximumExclusive: number): Condition<TPayload, TMeta>;
export declare function truthy<TPayload extends JsonMap = JsonMap, TMeta extends JsonMap = JsonMap>(path: string): Condition<TPayload, TMeta>;
export declare function actionIs<TPayload extends JsonMap = JsonMap, TMeta extends JsonMap = JsonMap>(action: string): Condition<TPayload, TMeta>;
export declare function actorTypeIs<TPayload extends JsonMap = JsonMap, TMeta extends JsonMap = JsonMap>(type: string): Condition<TPayload, TMeta>;
export declare function providerIs<TPayload extends JsonMap = JsonMap, TMeta extends JsonMap = JsonMap>(provider: string): Condition<TPayload, TMeta>;
export declare function tagIncludes<TPayload extends JsonMap = JsonMap, TMeta extends JsonMap = JsonMap>(tag: string): Condition<TPayload, TMeta>;
export declare function resourceTypeIs<TPayload extends JsonMap = JsonMap, TMeta extends JsonMap = JsonMap>(type: string): Condition<TPayload, TMeta>;
export declare function amountAbove<TPayload extends JsonMap = JsonMap, TMeta extends JsonMap = JsonMap>(minimumExclusive: number, path?: string): Condition<TPayload, TMeta>;
export declare function confidenceBelow<TPayload extends JsonMap = JsonMap, TMeta extends JsonMap = JsonMap>(maximumExclusive: number, path?: string): Condition<TPayload, TMeta>;
export declare function flag<TPayload extends JsonMap = JsonMap, TMeta extends JsonMap = JsonMap>(path: string): Condition<TPayload, TMeta>;
export declare function reasonFromMatches(matches: string[]): string;
export declare function createPolicyContext<TPayload extends JsonMap = JsonMap, TMeta extends JsonMap = JsonMap>(request: PolicyContext<TPayload, TMeta>['request'], getter: (path: string) => JsonValue | undefined): PolicyContext<TPayload, TMeta>;
